# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"\x1f\n\x0fGetPostsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"L\n\x10GetPostsResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\x12\x13\n\x0btotal_likes\x18\x03 \x01(\x05\"\x16\n\x14\x43ustomMessageRequest\"(\n\x15\x43ustomMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x98\x01\n\x05Posts\x12=\n\x08GetPosts\x12\x16.posts.GetPostsRequest\x1a\x17.posts.GetPostsResponse\"\x00\x12P\n\x11SendCustomMessage\x12\x1b.posts.CustomMessageRequest\x1a\x1c.posts.CustomMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETPOSTSREQUEST']._serialized_start=22
  _globals['_GETPOSTSREQUEST']._serialized_end=53
  _globals['_GETPOSTSRESPONSE']._serialized_start=55
  _globals['_GETPOSTSRESPONSE']._serialized_end=131
  _globals['_CUSTOMMESSAGEREQUEST']._serialized_start=133
  _globals['_CUSTOMMESSAGEREQUEST']._serialized_end=155
  _globals['_CUSTOMMESSAGERESPONSE']._serialized_start=157
  _globals['_CUSTOMMESSAGERESPONSE']._serialized_end=197
  _globals['_POSTS']._serialized_start=200
  _globals['_POSTS']._serialized_end=352
# @@protoc_insertion_point(module_scope)
