# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import posts_pb2 as posts__pb2


class PostsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosts = channel.unary_unary(
                '/posts.Posts/GetPosts',
                request_serializer=posts__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=posts__pb2.GetPostsResponse.FromString,
                )
        self.SendCustomMessage = channel.unary_unary(
                '/posts.Posts/SendCustomMessage',
                request_serializer=posts__pb2.CustomMessageRequest.SerializeToString,
                response_deserializer=posts__pb2.CustomMessageResponse.FromString,
                )


class PostsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCustomMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=posts__pb2.GetPostsRequest.FromString,
                    response_serializer=posts__pb2.GetPostsResponse.SerializeToString,
            ),
            'SendCustomMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCustomMessage,
                    request_deserializer=posts__pb2.CustomMessageRequest.FromString,
                    response_serializer=posts__pb2.CustomMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'posts.Posts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Posts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.Posts/GetPosts',
            posts__pb2.GetPostsRequest.SerializeToString,
            posts__pb2.GetPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendCustomMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.Posts/SendCustomMessage',
            posts__pb2.CustomMessageRequest.SerializeToString,
            posts__pb2.CustomMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
